# Gift Box User Service Configuration
server:
  port: 8081
  servlet:
    context-path: /user-service

spring:
  application:
    name: giftbox-user-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/giftbox_user
    username: postgres
    password: abc123ABC!@#
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  
  # Redis Configuration
  redis:
    host: localhost
    port: 6379
    password: 
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# JWT Configuration
jwt:
  secret: giftbox-secret-key-that-should-be-changed-in-production
  access-token-validity: 3600  # 1 hour
  refresh-token-validity: 86400  # 24 hours

# Security Configuration
security:
  jwt:
    secret: ${jwt.secret}
    access-token-validity: ${jwt.access-token-validity}
    refresh-token-validity: ${jwt.refresh-token-validity}

# Logging Configuration
logging:
  level:
    com.giftbox.userservice: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-service.log

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Application Information
info:
  app:
    name: Gift Box User Service
    description: User management and authentication service for Gift Box platform
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}

# Cache Configuration
spring.cache:
  type: redis
  redis:
    time-to-live: 600000  # 10 minutes
    cache-null-values: false
