apisix:
  node_listen: 9080
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

nginx_config:
  error_log: "/dev/stderr"
  error_log_level: "warn"
  worker_processes: "auto"
  worker_rlimit_nofile: 20480
  event:
    worker_connections: 10620
    multi_accept: "on"
  http:
    access_log: "/dev/stdout"
    keepalive_timeout: 60s
    client_max_body_size: 1m
    client_body_buffer_size: 8k
    client_header_buffer_size: 4k
    large_client_header_buffers: 4 8k
    underscores_in_headers: "on"
    real_ip_header: "X-Real-IP"
    real_ip_recursive: "on"
    real_ip_from:
      - "127.0.0.0/24"
      - "192.168.0.0/16"
      - "172.16.0.0/12"
      - "10.0.0.0/8"
    lua_package_path: "/usr/local/apisix/?.lua;/usr/local/apisix/?/init.lua;;"
    lua_package_cpath: "/usr/local/apisix/?.so;;"
    lua_socket_log_errors: "off"
    lua_shared_dict:
      prometheus_metrics: 1m
      plugin-limit-conn: 10m
      plugin-limit-count: 10m
      plugin-limit-req: 10m
      ip-restriction: 1m
      plugin-limit-req-redis-cluster: 1m
      upstream-healthcheck: 1m
      worker-events: 1m
    lua_max_pending_timers: 1024
    lua_max_running_timers: 256
    upstream:
      keepalive_pool:
        size: 320
        idle_timeout: 60s
    upstream_keepalive_requests: 1000
    upstream_keepalive_timeout: 60s
    init_worker_by_lua_block: "require('apisix').http_init_worker()"
    init_by_lua_block: "require('apisix').http_init()"
    server:
      listen: 9080
      server_name: _;
      location:
        "~ ^/apisix/":
          content_by_lua_block: "require('apisix').http_access_phase() require('apisix').http_header_filter_phase() require('apisix').http_body_filter_phase() require('apisix').http_log_phase()"
        "/":
          content_by_lua_block: "require('apisix').http_access_phase() require('apisix').http_header_filter_phase() require('apisix').http_body_filter_phase() require('apisix').http_log_phase()"