apisix:
  node_listen: 9080
  enable_admin: true
  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin
  enable_debug: false
  enable_admin_cors: true
  config_center: yaml
  router:
    http: 'radixtree_uri'
  plugin_attr:
    prometheus:
      export_addr:
        ip: "0.0.0.0"
        port: 9091
